#!/bin/bash

#This program records a trip in the file of a car provided
if [ $# -ne 2 ]; then
	echo "Error with the number of arguments"
	echo "Enter License distance"
	exit
fi
km=$2
license=$1
#check if file exist. Using the ! to ask if the file does NOT exist.
if [ ! -f "$license.txt" ]; then
	echo "Car does not exist"
	exit
fi
echo "$km" >> $license.txt
bash frame "Trip recorded successfully"
